/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.view;

import com.socket.Mensagem;
import com.socket.SocketCliente;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.UIManager;

/**
 *
 * @author Gabriel
 */
public class FrameChatClient extends javax.swing.JFrame {
    public SocketCliente socketCliente;
    public Mensagem msg;
    public File file;
    public String dir;
    
    
    /**
     * Creates new form FrameChatClient
     */
    public FrameChatClient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldMSG = new javax.swing.JTextField();
        jTextFieldARQ = new javax.swing.JTextField();
        jButtonMSG = new javax.swing.JButton();
        jButtonDir = new javax.swing.JButton();
        jButtonArq = new javax.swing.JButton();
        jButtonConectar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonMSG.setText("EnviaMSG");
        jButtonMSG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMSGActionPerformed(evt);
            }
        });

        jButtonDir.setText("...");
        jButtonDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDirActionPerformed(evt);
            }
        });

        jButtonArq.setText("EnviaARQ");
        jButtonArq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonArqActionPerformed(evt);
            }
        });

        jButtonConectar.setText("Conectar");
        jButtonConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConectarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextFieldARQ, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDir))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonConectar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTextFieldMSG))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonMSG)
                    .addComponent(jButtonArq))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonConectar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMSG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMSG))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldARQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDir)
                    .addComponent(jButtonArq))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConectarActionPerformed
        try {
            socketCliente = new SocketCliente();
        } catch (IOException ex) {
            Logger.getLogger(FrameChatClient.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButtonConectarActionPerformed

    private void jButtonMSGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMSGActionPerformed
       msg = new Mensagem(1, jTextFieldMSG.getText());
       jTextFieldMSG.setText("");
        try {
            socketCliente.enviaMSG(msg);
        } catch (IOException ex) {
            Logger.getLogger(FrameChatClient.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButtonMSGActionPerformed

    private void jButtonDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDirActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        int opt = fileChooser.showDialog(this, "Escolha o arquivo");
        {
            this.file = fileChooser.getSelectedFile();
        }
        
        if(file != null){
            if(!file.getName().isEmpty()){
                String str;
                
                if(jTextFieldARQ.getText().length() > 30){
                    String t = file.getPath();
                    str = t.substring(0, 20) + " [...] " + t.substring(t.length() - 20, t.length());
                }
                else{
                    str = file.getPath();
                }
                jTextFieldARQ.setText(str);
            }
        }
    }//GEN-LAST:event_jButtonDirActionPerformed

    private void jButtonArqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonArqActionPerformed
        msg = new Mensagem(2, file);
        try {
            //jTextArea1.append("Cliente > Servidor: O Arquivo"+file.getName()+" foi enviado");
            socketCliente.enviaMSG(msg);
        } catch (IOException ex) {
            Logger.getLogger(FrameChatClient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonArqActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try{
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        }
        catch(Exception ex){
            System.out.println("Look & Feel Exception");
        } 
                
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameChatClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonArq;
    private javax.swing.JButton jButtonConectar;
    private javax.swing.JButton jButtonDir;
    private javax.swing.JButton jButtonMSG;
    private javax.swing.JTextField jTextFieldARQ;
    private javax.swing.JTextField jTextFieldMSG;
    // End of variables declaration//GEN-END:variables
}
